### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by ogezue** [psy2k/NMPopUpView#14]
Support for cocoapods would be great.

**Comment by psy2k** [comment]
@ogezue Cocoapods will be supported in the next version alongside iOS 9 and Swift 2.0.

**Comment by datomnurdin** [comment]
How about now?

**Comment by psy2k** [comment]
@datomnurdin Cocoapods support is coming late next week.

**Comment by datomnurdin** [comment]
TQMV!!

**Comment by psy2k** [comment]
@ogezue @datomnurdin Could you please try to use the lib with cocoapods? Add `pod 'NMPopUpViewSwift'` to your pod file and run `pod install`. The lib is in Swift so add `use_frameworks!` in order to tell the build tool that you want to use embedded frameworks. If Cocoapods cannot find the repo, force a spec repo update using these commands in the terminal: `pod repo remove master` and `pod setup`. Let me know if everything worked properly.

After installation via Cocapods the .xib files are in the framework bundle so you should load them using:

``````````swift
    @IBAction func showPopUp(sender: AnyObject) {
        let bundle = NSBundle(forClass: PopUpViewControllerSwift.self)
        if (UIDevice.currentDevice().userInterfaceIdiom == .Pad)
        {
            self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPad", bundle: bundle)
            self.popViewController.title = "This is a popup view"
            self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
        } else
        {
            if UIScreen.mainScreen().bounds.size.width > 320 {
                if UIScreen.mainScreen().scale == 3 {
                    self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPhone6Plus", bundle: bundle)
                    self.popViewController.title = "This is a popup view"
                    self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
                } else {
                    self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPhone6", bundle: bundle)
                    self.popViewController.title = "This is a popup view"
                    self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
                }
            } else {
                self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController", bundle: bundle)
                self.popViewController.title = "This is a popup view"
                self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
            }
        }
    }
`````````````````

**Comment by dflateau** [comment]
I'm trying to use the swift cocoapod in an objective-c project. I use frameworks in my pod file, and @import NMPopUpViewSwift; in my .m file. Xcode seems to be OK with this. However, PopUpViewController is not a recognized class. Any ideas?

**Comment by psy2k** [comment]
@dflateau can you post some code please?

**Comment by dflateau** [comment]
Sure.

Pod file:

<source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'RaptureXML', '~> 1.0'
pod 'AFNetworking', '~> 2.6'
pod 'UICKeyChainStore', '~> 2.0'
pod 'IBActionSheet', '~> 0.0'
pod 'iTunesSearch', '~> 1.1'
pod 'FBSDKCoreKit', '~> 4.6'
pod 'FBSDKLoginKit', '~> 4.6'
pod 'FBSDKShareKit', '~> 4.6'
pod 'BaseModel', '~> 2.6'
pod 'HRCoder', '~> 1.3'
pod 'NMPopUpViewSwift', '~> 3.0'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited), PodsDummy_Pods=SomeOtherNamePodsDummy_Pods'
        end
    end
end


In obj-c .m file:

@import NMPopUpViewSwift;

...

  PopUpViewController *popViewController = [[PopUpViewController alloc]
                                                       initWithNibName:@"PopUpViewController" bundle:nil];

where it says that PopUpViewController is an unknown type name.

**Comment by psy2k** [comment]
@dflateau the class is named `PopUpViewControllerSwift`, so the proper way to initialize the controller is:

```````objc
PopUpViewControllerSwift *popViewController = [[PopUpViewControllerSwift alloc]
                                              initWithNibName:@"PopUpViewController" bundle:nil];
````````
