### ISSUE TITLE
Crash when click closed

### ISSUE THREAD

**Issue by tanbuu1205** [psy2k/NMPopUpView#18]
In swift version.
I have issue when click on close button. And find out how to fix it.
On MainViewController if should be 
```
var popViewController : PopUpViewControllerSwift = PopUpViewControllerSwift(nibName: "PopUpViewController", bundle: nil)
popViewController.title = "This is a popup view"
addChildViewController(popViewController)
popViewController.showInView(self.view, withImage: UIImage(named: "01"), withMessage: "You just triggered a great popup window", animated: true)
popViewController.didMoveToParentViewController(self)
```

Add 2 lines of code : 
```
addChildViewController(popViewController)
```
```
popViewController.didMoveToParentViewController(self)
```

**Comment by psy2k** [comment]
@tanbuu1205 You have to declare the popup property in your class and not within your method so it is not get released. This issue is already discussed so I am closing this. https://github.com/psy2k/NMPopUpView/issues/9
