### ISSUE TITLE
Connect button doesnt work

### ISSUE THREAD

**Issue by Persilos** [psy2k/NMPopUpView#19]
Hi,
I work in swift. I imported the .xib and PopUpViewControllerSwift.swift files, design my layout in the xib files, link my outlet, and write my actions methods for buttons.
Treatment i do on my outlet (for example, add border in my button) work perfectly. But when i connect a button with a @IBAction, connect work well, but when i click on the button, nothing happens (if i put a breakpoint, i notice this doesnt enter in the method)

File's Owner
<img width="260" alt="capture d ecran 2015-10-22 a 15 30 11" src="https://cloud.githubusercontent.com/assets/8830732/10667023/70b74468-78d5-11e5-8ff2-d0925811923c.png">

<img width="257" alt="capture d ecran 2015-10-22 a 16 02 21" src="https://cloud.githubusercontent.com/assets/8830732/10667071/ac2c0bb4-78d5-11e5-819e-32dbfd60089b.png">

My method closePopUp
<img width="394" alt="capture d ecran 2015-10-22 a 15 29 21" src="https://cloud.githubusercontent.com/assets/8830732/10667084/bae92fa6-78d5-11e5-861e-73b3cce9b5cf.png">

**Comment by psy2k** [comment]
@Persilos please provide more info regarding this. Is the button the top view or is another view over it? Please provide that view hierarchy from your .xib file.

**Comment by MossDevlper** [comment]
Hi, I have the same problem...

Here is the view hierarchy i´m using...
<img width="270" alt="screen shot 2015-10-24 at 8 15 54 pm" src="https://cloud.githubusercontent.com/assets/13543812/10713573/2428b146-7a8c-11e5-89d1-dbf64238ccbe.png">

And this are the methods i´m using...
<img width="269" alt="screen shot 2015-10-24 at 8 16 03 pm" src="https://cloud.githubusercontent.com/assets/13543812/10713576/4b15fa8e-7a8c-11e5-859d-d6e6b92aac6b.png">
<img width="378" alt="screen shot 2015-10-24 at 8 16 17 pm" src="https://cloud.githubusercontent.com/assets/13543812/10713577/56f14f16-7a8c-11e5-804c-08213c179b4c.png">

Problem is that when i click my button, it gets highlighted, but the @IBAction doesn´t trigger.

**Comment by MossDevlper** [comment]
I found the solution looking on other issues, i just changed my popup initializer to the beginning like this...
<img width="623" alt="screen shot 2015-10-24 at 8 37 37 pm" src="https://cloud.githubusercontent.com/assets/13543812/10713628/2549051e-7a8f-11e5-901c-38a13adf7d68.png">
And this is the function where I use it...
<img width="448" alt="screen shot 2015-10-24 at 8 37 48 pm" src="https://cloud.githubusercontent.com/assets/13543812/10713630/337a861c-7a8f-11e5-95cc-85c9e1b8b79d.png">

And the rest is history... Hope this can also help you @Persilos .

**Comment by psy2k** [comment]
@MossDevlper That is not totally correct because you are assigning the .xib for the iPhone 4/4s/5/5s. It is better to declare it as forced unwrapped optional (`var popViewController : PopUpViewControllerSwift!`) in your properties and initialize it within your method, so you use the correct .xib.

`````````````swift
 @IBAction func showPopUp(sender: AnyObject) {
        let bundle = NSBundle(forClass: PopUpViewControllerSwift.self)
        if (UIDevice.currentDevice().userInterfaceIdiom == .Pad)
        {
            self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPad", bundle: bundle)
            self.popViewController.title = "This is a popup view"
            self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
        } else
        {
            if UIScreen.mainScreen().bounds.size.width > 320 {
                if UIScreen.mainScreen().scale == 3 {
                    self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPhone6Plus", bundle: bundle)
                    self.popViewController.title = "This is a popup view"
                    self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
                } else {
                    self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController_iPhone6", bundle: bundle)
                    self.popViewController.title = "This is a popup view"
                    self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
                }
            } else {
                self.popViewController = PopUpViewControllerSwift(nibName: "PopUpViewController", bundle: bundle)
                self.popViewController.title = "This is a popup view"
                self.popViewController.showInView(self.view, withImage: UIImage(named: "typpzDemo"), withMessage: "You just triggered a great popup window", animated: true)
            }
        }
    }
``````````````

**Comment by MossDevlper** [comment]
Actually since I'm using autolayout i don´t have the problem of choosing different layouts... Even thow I'm going to give a try on the way you mention, to have the declaration made once popUpView is needed.

**Comment by psy2k** [comment]
Just merged a branch that uses cocoapods! You can give it a try too if you like.

**Comment by Persilos** [comment]
Sorry for the late response.

Here is the hierarchy.
<img width="1165" alt="capture d ecran 2015-10-26 a 17 44 55" src="https://cloud.githubusercontent.com/assets/8830732/10735528/bdf8adbc-7c08-11e5-80a1-89904257ee84.png">

@MossDevlper your solution doesnt work for me :(

<img width="387" alt="capture d ecran 2015-10-26 a 17 47 20" src="https://cloud.githubusercontent.com/assets/8830732/10735592/1793be34-7c09-11e5-85ce-cab43070acac.png">

<img width="644" alt="capture d ecran 2015-10-26 a 17 48 00" src="https://cloud.githubusercontent.com/assets/8830732/10735600/22f780bc-7c09-11e5-95f1-09aca9beb348.png">

I really dont understand, i used NMPopUpView a lot of time in all of my previous projects and this always works perfectly, this is the first time i have a problem like this..

**Comment by Persilos** [comment]
Okay my bad, @MossDevlper  your fix work perfectly. I dont see the "var" key in my IBAction btnParametre :D
