### ISSUE TITLE
Crash on close pop up view

### ISSUE THREAD

**Issue by LadyDeveloper** [psy2k/NMPopUpView#22]
When I tap on button for close the popup view, app crashes without breakpoint exception, but Xcode show this : "EXC_BAD_ACCESS".

**Comment by psy2k** [comment]
@LadyDeveloper Declare the popup as a strong property in your view controller.

**Comment by psy2k** [comment]
@LadyDeveloper More info on this can be found here https://github.com/psy2k/NMPopUpView/issues/18 and #9

**Comment by LadyDeveloper** [comment]
Thank you!
