### ISSUE TITLE
Migrate To Swift 3

### ISSUE THREAD

**Issue by Gerst20051** [psy2k/NMPopUpView#23]
Branch: https://github.com/Gerst20051/NMPopUpView/tree/swift3
MR: https://github.com/psy2k/NMPopUpView/pull/24

**Comment by psy2k** [comment]
@Gerst20051 already supported. Just waiting for cocoapods update. https://github.com/psy2k/NMPopUpView/commit/b751d5e3bed0b95395c6ed3dacd114ad0b97c271

**Comment by Gerst20051** [comment]
Okay great just let me know when you get it updated.

**Comment by psy2k** [comment]
@Gerst20051 cocoapods just got updated to version 1.1, so I will upload the new version very soon and will close this issue when the new version is up and running.

**Comment by psy2k** [comment]
Pod is now updated to version 4.0.2. Just a `pod update` will get you the latest version

**Comment by Gerst20051** [comment]
thanks @psy2k you da bomb 👍
