### ISSUE TITLE
Add GIF to README

### ISSUE THREAD

**Issue by lfarah** [psy2k/NMPopUpView#26]
Hey @psy2k, your lib is really cool, but your README can have some improvements. Since you have an UI Library, it would be good to add a gif to show to devs how it looks like. You can get some inspiration from [this lib](https://github.com/Orderella/PopupDialog)

**Comment by psy2k** [comment]
@lfarah already had a .gif. It was on my dropbox public folder and it just stopped working with the recent dropbox changes. Now it is fixed https://github.com/psy2k/NMPopUpView/commit/c636bc9a5ae13a1f289ec7cddda414555e5305cf
