### ISSUE TITLE
Objective-C button close not works

### ISSUE THREAD

**Issue by Paul75** [psy2k/NMPopUpView#8]
Hello,

I use only `Objective-C` version, not `Swift`.

- I integrate PopUpViewController.h and PopUpViewController.m.
- I create a .xib with button close like your exemple.
- I code it to open : 
`````objective-c
- (void)openPopup
{
    PopUpViewController *popViewController = [[PopUpViewController alloc] initWithNibName:@"NbArticlesPopUpViewController" bundle:nil];
    
    [popViewController setTitle:@"This is a popup view"];
     [popViewController showInView:self.parentViewController.view
     withImage:[UIImage imageNamed:@"yourImage"]
     withMessage:@"Message" animated:YES];
}
`````

The popup launch but the button close crash application.…

Thanks for help....

**Comment by psy2k** [comment]
@Paul75 are you using the Swift version of my code or the Objective-C version?

**Comment by Paul75** [comment]
The objective c



Sur 13 févr. 2015 09:55, à 09:55, Nikos Maounis <notifications@github.com> a écrit:

**Comment by psy2k** [comment]
Did you try the .xibs available in the repo? You have to wire the close action to the xib file. Also you may find the solution for issue #7 useful. Let me know if you still have issue with this and post the crash message if you can.

**Comment by Paul75** [comment]
I use the xibs Who are un thé package version ...



Sur 13 févr. 2015 11:02, à 11:02, Nikos Maounis <notifications@github.com> a écrit:

**Comment by psy2k** [comment]
@Paul75 I've just tested it and it works properly on both the Swift and the Objective-C version (as long as you set the file owner to the .xib files to the version you want to use -ObjC or Swift-. Post the crash log please so I can help you further.

**Comment by Paul75** [comment]
I test it with the exemple and it not found the import -swift.h



Sur 14 févr. 2015 09:54, à 09:54, Nikos Maounis <notifications@github.com> a écrit:

**Comment by psy2k** [comment]
@Paul75 are you using Xcode 6? -swift.h file is an auto-generated file for using Swift classes in Objective-C. Also your project should target iOS 7 and above.

**Comment by Paul75** [comment]
But i must configure the project specially ? 



Sur 14 févr. 2015 10:07, à 10:07, Nikos Maounis <notifications@github.com> a écrit:

**Comment by Paul75** [comment]
But i must incorpore the swift version if file ? 



Sur 14 févr. 2015 10:07, à 10:07, Nikos Maounis <notifications@github.com> a écrit:

**Comment by psy2k** [comment]
@Paul75 if you want to use the Objective-C version, just add to your project only the Objective-C classes and change the file owner of the .xibs to PopUpViewController (the default is PopUpViewControllerSwift) as described here #7.

**Comment by Paul75** [comment]
Okay it works...


I have a another question : I can do a form (add textfield, others.…) and
add button validate ?

Thanks

2015-02-14 10:20 GMT+01:00 Nikos Maounis <notifications@github.com>:

> @Paul75 <https://github.com/Paul75> if you want to use the Objective-C
> version, just add to your project only the Objective-C classes and change
> the file owner of the .xibs to PopUpViewController (the default is
> PopUpViewControllerSwift) as described here #7
> <https://github.com/psy2k/NMPopUpView/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psy2k/NMPopUpView/issues/8#issuecomment-74368206>.
>



-- 
Paul

**Comment by psy2k** [comment]
@Paul75 you can customize the popup as you like and add any UI element you want. It is just like any other iOS view.

**Comment by Paul75** [comment]
Thanks.

To modify I must hange functions to send datas ? change
PopUpViewController.h and PopUpViewController.m ?

Thanks a lot :)

2015-02-15 14:00 GMT+01:00 Nikos Maounis <notifications@github.com>:

> Closed #8 <https://github.com/psy2k/NMPopUpView/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psy2k/NMPopUpView/issues/8#event-235971838>.
>



-- 
Paul

**Comment by psy2k** [comment]
@Paul75 Yes you can add any IBOutlet and the corresponding actions and functions in PopUpViewController.h and .m files like you do with any other class or view.

**Comment by Paul75** [comment]
Thanks a lot :)

2015-02-15 17:08 GMT+01:00 Nikos Maounis <notifications@github.com>:

> @Paul75 <https://github.com/Paul75> Yes you can add any IBOutlet and the
> corresponding actions and functions in PopUpViewController.h and .m files
> like you do with any other class or view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psy2k/NMPopUpView/issues/8#issuecomment-74423373>.
>



-- 
Paul

**Comment by psy2k** [comment]
More info on a similar issue are provided here #9

**Comment by sai487** [comment]
Hiii I'm not getting response to the button.
please help me.
i'm using objective C

**Comment by psy2k** [comment]
@sai487 make sure that you keep a strong reference to the popup in your code. See the readme file for more information.
